# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87e4b243f790a18b0a022a6df759786114cb9006854c84b52238d8a4b089d13945d20cda3d24c8f9f269a82e04f10c19eccad7f494010269ccd1e5e90195ff90

test:
  secret_key_base: 987879c57a239bc738547097d7f575a74d97b37961ca5bbd05c6a5a44bc91708f1a3c457dcd12533a087fa5353064471aa16a4a22188f080f9e4c16c7853fee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
